### ISSUE TITLE
[x] ERROR: 'URLError' object has no attribute 'message'                      

### ISSUE THREAD

**Issue by swiss-mi** [boxug/trape#322]
I do not understand why it is doing this after I enter URL and port I get this message: [x] ERROR: 'URLError' object has no attribute 'message'

**Comment by mbslinux** [comment]
having the same problem..

**Comment by zohairhadi** [comment]
the same issue here

**Comment by SirZexx** [comment]
> I do not understand why it is doing this after I enter URL and port I get this message: [x] ERROR: 'URLError' object has no attribute 'message'

Hey, I had the same issue with it but after storming through Error I Found out that my Ngrok API key had extra chracter it looked like this :"./ngrok authtoken 20lxqyBgsoEplfNHYtRTJtwHLGRj1h2b31241kjb94tPFvg1h23vT" but then i changed it to just "20lxqyBgsoEplfNHYtRTJtwHLGRj1h2b31241kjb94tPFvg1h23vT" and it worked fine for me. You can change it by going to "/root/trape/trape.config/" and remove extra thing like "./ngrok authtoken" nad it will work

> the same issue here



> having the same problem..

**Comment by Likt228** [comment]
> > Я не понимаю, почему это происходит после того, как я ввожу URL-адрес и порт, я получаю это сообщение: [x] ОШИБКА: объект «URLError» не имеет атрибута «сообщение».
> 
> Эй, у меня была такая же проблема с этим, но после штурма через ошибку я обнаружил, что мой ключ API NGROK был очень похож, она выглядела так: «. хорошо для меня. Вы можете изменить его, перейдя в «/root/trape/trape.config/» и удалив лишние вещи, такие как «./ngrok authtoken», и это будет работать.
> 
> > та же проблема здесь
> 
> > такая же проблема..
I don't understand how I should do it anyway the same error please help)))

**Comment by Likt228** [comment]
I don't understand how I should do it anyway the same error please help)))

**Comment by god2106** [comment]
> 

nope doesnt work

**Comment by SirZexx** [comment]
> > 
> 
> nope doesnt work

show me your "trape.config" file and i'll see what i can do.

**Comment by deceitofjudas** [comment]
not working for me either getting the same issue tried multiple different urls

**Comment by rbrtjns90** [comment]
The error is because the api changed on displaying an error message between the versions of python. e.message -> str(e).

I fixed a bunch of these bugs.

https://github.com/rbrtjns90/trape

**Comment by dzen14** [comment]
it still doesn't work I still get the same error message 'URLError' object has no attribute 'message'

**Comment by dzen14** [comment]
it still doesn't work I still get the same error message 'URLError' object has no attribute 'message'
